### PR TITLE
I will merge your PR successfully for 70$(Open to see proof of work!)

### PR DESCRIPTION
**Pull request by zakimzf**
### I will automerge your PR successfully for a mere 70$ fee  which would be payable only after successful completion of work in crypto.(I won't ask you to send funds beforehand so, you can rest assured its legit!)** 

I know getting your PR to automerge in token-list is a daunting task for many..no matter how many times you submit a PR it gets rejected for some reason. I have got your back! If you need to get your token-listed quickly so that you could focus on distributing it ,i'm your guy! I could also bulk add if you have many tokens at a discount! I have helped many tokens get listed on Solana. Here's a few of them you can review:

- SOLR token : https://github.com/solana-labs/token-list/pull/23613
- Collider coin : https://github.com/solana-labs/token-list/pull/23398
- CHWY token : https://github.com/solana-labs/token-list/pull/22839
- CHEWY token : https://github.com/solana-labs/token-list/pull/22758
- Billi Brothers token : https://github.com/solana-labs/token-list/pull/20567
- Wcoin token : https://github.com/solana-labs/token-list/pull/19249
- Clergy666 token  : https://github.com/solana-labs/token-list/pull/19137
- Metasek token  : https://github.com/solana-labs/token-list/pull/18144
- Local 73 coin  : https://github.com/solana-labs/token-list/pull/17914
- Nest token : https://github.com/solana-labs/token-list/pull/17824
- Ribbit token : https://github.com/solana-labs/token-list/pull/17463
- Gamify token : https://github.com/solana-labs/token-list/pull/17258
- Meta4 Token : https://github.com/solana-labs/token-list/pull/17231
- GMASK Token : https://github.com/solana-labs/token-list/pull/16951
- Alpha Token : https://github.com/solana-labs/token-list/pull/16501
- Dokdo Coin : https://github.com/solana-labs/token-list/pull/16340
- Cypher Token : https://github.com/solana-labs/token-list/pull/15961
- Ground Token : https://github.com/solana-labs/token-list/pull/15588
- DMP coin : https://github.com/solana-labs/token-list/pull/14613
- ShuShi Token : https://github.com/solana-labs/token-list/pull/14399
- Punkz Token : https://github.com/solana-labs/token-list/pull/14286
- BMXHUB Token : https://github.com/solana-labs/token-list/pull/14094
- Linux Token : https://github.com/solana-labs/token-list/pull/14076
- New Transformers Token : https://github.com/solana-labs/token-list/pull/13751
- AIM wealth coin : https://github.com/solana-labs/token-list/pull/13008
- MetaVersana : https://github.com/solana-labs/token-list/pull/12715
- Fone Token : https://github.com/solana-labs/token-list/pull/12697
- ZEN Token : https://github.com/solana-labs/token-list/pull/6005
- SolSquid Token : https://github.com/solana-labs/token-list/pull/5798
- Gravity Token : https://github.com/solana-labs/token-list/pull/5794

Here's how it works: I will open a new PR on your behalf for you token based on the details you provided. It passes all the checks  and qualifies for automerge. I will ask you to proceed with the payment (BNB/SOL) which if you failed to send in the next 10 mins , i will close the PR and you wont benefit in any way! That's it !

### Please respond to this via your personal email or telegram rather then directly replying inorder to speed up the process!

**Contact me:** 
**Telegram(preferred):** https://t.me/zakimzf
**Email:** zaki.faiz4@gmail.com with the subject " Need you to create a new PR"

### CODE REVIEW

**Comment by SquareandCompass** [comment]
Let's do this. Thanks. I would like to know after how it was done so as to know next round.

**Comment by SquareandCompass** [comment]
You will need to let me know when so as to be near. I will have to step out in about 30 minutes and be back within 2 hours. 2:14 PM my time now so let me know when you will start.

**Comment by zakimzf** [comment]
Hi thanks for reaching out! Let's get in touch contact me on telegram
@zakimzf

**Comment by Ditonionb** [comment]
Need you to create a new PR

**Comment by zakimzf** [comment]
Great! Contact me on telegram @zakimzf

**Comment by metasuite** [comment]
Why are you charging $70?

**Comment by joefitter** [comment]
github is not an advertising platform. Reported

**Comment by svm80** [comment]
Ok

**Comment by zakimzf** [comment]
Thanks for reaching out! If you could contact me on telegram @zakimzf then
i can proceed further.

PS: if you don't use telegram, then send any of your social handle that you
have.(whatsapp,ig,fb,twitter..)

**Pull request merged**
